name: Record Screenshots (main)

on:
  push:
    branches: [master]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  record:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Record screenshots
        run: ./gradlew composeApp:recordRoborazziDebug --stacktrace

      - name: Publish screenshots to screenshots branch (main/)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: composeApp/screenshots
          publish_branch: screenshots
          destination_dir: main
          keep_files: true
